### ISSUE TITLE
How to choose which store/state get persisted?

### ISSUE THREAD

**Issue by folamy** [iendeavor/pinia-plugin-persistedstate-2#11]
I am using Nuxt 3, and I don't want to persist all the store, how do I specify the store(s) that get persisted?

**Comment by iendeavor** [comment]
We have the `persist` option (maybe unclearly named):

To disable [default behavior](https://github.com/iendeavor/pinia-plugin-persistedstate-2#common-options) (persist all stores):

```ts
createPersistedStatePlugin({ persist: false })
```

To [specify](https://github.com/iendeavor/pinia-plugin-persistedstate-2#store-options) the store(s) that get persisted:

```ts
defineStore(
  'setup-store',
  () => ({}),
  {
    persistedState: {
      persist: true
    },
  },
)
```

Related issue: #6

**Comment by iendeavor** [comment]
For `state`, you could use `includePath` and/or `excludePath` option.

Example: https://github.com/iendeavor/pinia-plugin-persistedstate-2/blob/385be7a24596130fee960ad58bb1b71e57772cfd/tests/index.test.ts#L304-L317

**Comment by folamy** [comment]
> For `state`, you could use `includePath` and/or `excludePath` option.
> 
> For example:
> 
> https://github.com/iendeavor/pinia-plugin-persistedstate-2/blob/385be7a24596130fee960ad58bb1b71e57772cfd/tests/index.test.ts#L444-L462

I tried this but it didn't work!

```js
import { acceptHMRUpdate, defineStore } from 'pinia'
// import { useToast, POSITION } from 'vue-toastification'
import { actions } from './actions'
import { getters } from './getters'
import type { Address } from '~/model/user'

// const toast = useToast()

export const useUserStore = defineStore('userStore', {
  // @ts-ignore
  state: () => ({
    addresses: [] as Array<Address>,
    selectedId: '' as string
  }),

  actions: actions(),
  getters: getters()

  // getters: getters()
}, {
  persistedState: {
    persist: false,
    excludePaths: ['addresses']
  }
})

if (import.meta.hot)
  import.meta.hot.accept(acceptHMRUpdate(useUserStore, import.meta.hot))

`

**Comment by iendeavor** [comment]
@folamy 

The above answer if for setup-style store, if you use option-style store just remove one line:

```diff
export const useUserStore = defineStore('userStore', {
  // @ts-ignore
  state: () => ({
    addresses: [] as Array<Address>,
    selectedId: '' as string
  }),

  actions: actions(),
  getters: getters()

  // getters: getters()
- }, {
  persistedState: {
    persist: false
  }
})
```

I create an option store example here: https://stackblitz.com/edit/vitejs-vite-v2uak2?file=src%2FApp.vue&terminal=dev

Hope this helps you :smile:.

**Comment by folamy** [comment]
Wow! It works!

> @folamy
> 
> The above answer is for setup-style store, if you use option-style store just remove one line:
> 
> ```diff
> export const useUserStore = defineStore('userStore', {
>   // @ts-ignore
>   state: () => ({
>     addresses: [] as Array<Address>,
>     selectedId: '' as string
>   }),
> 
>   actions: actions(),
>   getters: getters()
> 
>   // getters: getters()
> - }, {
>   persistedState: {
>     persist: false
>   }
> })
> ```
> 
> I create an option store example here: https://stackblitz.com/edit/pinia-plugin-persistedstate-2-issue-11?file=src/App.vue
> 
> Hope this helps you smile.

Wow! Thanks it works.

**Comment by digitalit** [comment]
Any idea to exclude stuff in Composition API?

**Comment by renepardon** [comment]
> Any idea to exclude stuff in Composition API?

I would also be interested in how to use with VueJS 3 with composition API
