### ISSUE TITLE
Persisted State ignores includePaths and excludePaths

### ISSUE THREAD

**Issue by dskvr** [iendeavor/pinia-plugin-persistedstate-2#136]
**Describe the bug**
Persisted state options are being completely ignored.

**To Reproduce**
Pinia plugins:
- `pinia-shared-state`
- `pinia-plugin-persistedstate-2`

```
export const useTaskStore = defineStore('tasks', {
    state: () => ({ 
      someotherkey: 'ok',
      pending: new Array(),
      completed: new Array(),
      active: new Object(),
    }),
    getters: () => {
      // ...
    },
    actions: () => {
      // ...
    }
},
{
  persistedState: {
    //includePaths: ['someotherkey'],
    excludePaths: ['pending', 'completed', 'active'],
  }
)
```

Both `includePaths` and `excludePaths` result in undesired paths being persisted to state. 

**Expected behavior**
Keys explicitly set to not persist do not persist.

**Screenshots**
localStorage is deleted before each attempt. `active`, `pending` and `compelted` are still persisted to state. Absolutely crucial, because these keys store functions, which persisted state rightfully sanitizes, but for my use case is destructive.

Regardless, persisted state persists to persist unpersisted keys ;) 

![Screen Shot 2023-01-09 at 6 53 18 PM](https://user-images.githubusercontent.com/299465/211374655-44f00fb4-7097-4159-b553-d6c76ecadf1d.png)

**Desktop (please complete the following information):**
Linux, Windows, MacOs, all same behavior.
Chrome, Safari, Firefox, Branve, all same behavior.

**Smartphone (please complete the following information):**
all same behavior.

**Comment by iendeavor** [comment]
For option API, we need to define the persistedState in the second parameter:

```diff
import { defineStore } from 'pinia'
+ import 'pinia-plugin-persistedstate-2'

export const useTaskStore = defineStore('tasks',{
  state: () => ({
    someotherkey: 'ok',
    pending: new Array(),
    completed: new Array(),
    active: new Object(),
  }),
+ persistedState: {
+   includePaths: ['currentValue', 'someotherkey'],
+   // excludePaths: ['pending', 'completed', 'active']
+ },
-}, {
- persistedState: {
-   includePaths: ['currentValue', 'someotherkey'],
-   // excludePaths: ['pending', 'completed', 'active']
- },
})
```

docs: https://pinia.vuejs.org/core-concepts/plugins.html#adding-new-options

**Comment by dskvr** [comment]
Oh man, totally botched it, thank you!!!!
