### ISSUE TITLE
pinia-plugin-persistedstate-2 plugin supports async storage?

### ISSUE THREAD

**Issue by rendomnet** [iendeavor/pinia-plugin-persistedstate-2#156]
Can I use it with chrome storage? https://developer.chrome.com/docs/extensions/reference/storage
Also is there an event when store is rehydrated first time?

**Comment by rendomnet** [comment]
> [Yes](https://github.com/iendeavor/pinia-plugin-persistedstate-2#storage)

This is different storage.
I'm talking about chrome storage for browser extensions it is async.

**Comment by SeryiBaran** [comment]
> > [Yes](https://github.com/iendeavor/pinia-plugin-persistedstate-2#storage)
> 
> This is different storage. I'm talking about chrome storage for browser extensions it is async. For some funny reason they called it storage too.
> 
> Anyway it is working with [developer.chrome.com/docs/extensions/reference/storage](https://developer.chrome.com/docs/extensions/reference/storage)

As far as I know, this plugin accepts any synchronous/asynchronous storage - you just need to write a simple wrapper for setItem, getItem and removeItem.
