### ISSUE TITLE
On rehydration complete event.

### ISSUE THREAD

**Issue by rendomnet** [iendeavor/pinia-plugin-persistedstate-2#163]
I need to do some stuff after the state has been rehydrated.
Is there any onReady event?

**Comment by iendeavor** [comment]
You could use [`isReady`](https://github.com/iendeavor/pinia-plugin-persistedstate-2#store-properties).

**Comment by rendomnet** [comment]
> You could use [`isReady`](https://github.com/iendeavor/pinia-plugin-persistedstate-2#store-properties).
`isReady `checks if it is ready it is not usefull for me.
The thing is I want to show application only when hyrdration is completed.

**Comment by iendeavor** [comment]
> store.$persistedState.isReady: () => Promise<void>: Whether store is hydrated

The `isReady` is a promise which will be resolved after hydration.

**Comment by iendeavor** [comment]
For example, if you are using vue-router, you could pause navigation until store is hydrated:

```ts
router.beforeEach(async (to, from) => {
  const store = useCounterStore()
  await store.$persistedState.isReady()
})
```

ref: https://router.vuejs.org/guide/advanced/navigation-guards.html#global-before-guards

**Comment by rendomnet** [comment]
@iendeavor Oh okay, this promise returned undefined so I decided it is just checking and not waiting until it is rehydrated.

**Comment by rendomnet** [comment]
Can we make setup of **pinia-plugin-persistedstate-2** similiar to **pinia-plugin-persistedstate**

It is much cleaner to have pesisted-state settings inside **defineStore**

Something like this.
```
export const useStore = defineStore("store", {
  state: () => {
    return {
      someState: "hello pinia",
    };
  },
  persist: {
    getItem: async (storeId) => {
      
    },
    setItem: async (key, value) => {
     
    },
    removeItem: async (key) => {
      
    },
    onReady: async () => {}
  },
});
```
