### ISSUE TITLE
Better pinia-plugin-persistedstate-2 setup

### ISSUE THREAD

**Issue by rendomnet** [iendeavor/pinia-plugin-persistedstate-2#165]
Can we make setup of **pinia-plugin-persistedstate-2** similiar to **pinia-plugin-persistedstate**
It is much cleaner to have pesisted-state settings inside defineStore

Something like this.

```
export const useStore = defineStore("store", {
  state: () => {
    return {
      someState: "hello pinia",
    };
  },
  persist: {
    getItem: async (storeId) => {
      
    },
    setItem: async (key, value) => {
     
    },
    removeItem: async (key) => {
      
    },
    onReady: async () => {}
  },
});
```

**Comment by iendeavor** [comment]
Are you looking for [the store options](https://github.com/iendeavor/pinia-plugin-persistedstate-2#store-options)?

**Comment by rendomnet** [comment]
@iendeavor yes but it would be better to move `getItem`, `setItem`, `removeItem`, `onReady `inside the **store options**
