### ISSUE TITLE
setItem's value isn't `any`, but `string`, because serialization happens before calling storage.setItem().

### ISSUE THREAD

**Issue by Krzysztof-Dziardziel** [iendeavor/pinia-plugin-persistedstate-2#175]
![image](https://user-images.githubusercontent.com/56971803/217101590-022b8242-05d8-435c-953d-518d819f401d.png)
In the documentation it says that value can be `any`, but this is not true as the serialization happens in the library code before setItem is called.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/56971803/217101697-331680c4-80ad-45e2-b5a9-e45d6e86dcd9.png">

**Comment by Krzysztof-Dziardziel** [comment]
I was getting string as a fallback of serialize method, because it was returning console.log(state).

**Comment by iendeavor** [comment]
The serialization can be customized, e.g., you may want to store _objects_ to `IndexedDB`:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/22850435/217138210-2cec2171-9a8a-4c3c-bd7e-e79c8b7a66dc.png">

https://github.com/iendeavor/pinia-plugin-persistedstate-2#common-options .
