### ISSUE TITLE
Can't build after installing this package.

### ISSUE THREAD

**Issue by anburocky3** [iendeavor/pinia-plugin-persistedstate-2#20]
After building, `nuxi build` and previewing `nuxi start` it has this error.

```
[nuxt] [request error] [🍍]: getActivePinia was called with no active Pinia. Did you forget to install pinia?
        const pinia = createPinia()
        app.use(pinia)
This will fail in production.
  at useStore (/S:/dev-projects/anand-kali-projects/iragugal/.output/server/node_modules/pinia/dist/pinia.mjs:1631:19)
  at /S:/dev-projects/anand-kali-projects/iragugal/.output/server/chunks/server.mjs:5981:21
  at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
  at async /S:/dev-projects/anand-kali-projects/iragugal/.output/server/chunks/renderer.mjs:540:24
  at async /S:/dev-projects/anand-kali-projects/iragugal/.output/server/chunks/renderer.mjs:597:20
  at async /S:/dev-projects/anand-kali-projects/iragugal/.output/server/node_modules/h3/dist/index.mjs:417:19
  at async Server.nodeHandler (/S:/dev-projects/anand-kali-projects/iragugal/.output/server/node_modules/h3/dist/index.mjs:367:7)
```

**Comment by iendeavor** [comment]
Thanks for your feedback.

Can you provide a minimal reproduce repo or link?
We don't even know which nuxt version you are using. 😅

**Comment by iendeavor** [comment]
After installation, you must also install the plugin:
https://github.com/iendeavor/pinia-plugin-persistedstate-2#ssr

There are all examples for nuxt 2, 3 and bridge:
https://github.com/iendeavor/pinia-plugin-persistedstate-2/tree/main/examples

**Comment by anburocky3** [comment]
Thanks for the quick reply, i tried nuxt3 only.

Sorry to say that, i faced the build errors after using these packages. 

For the reproduce, here is the [repo](https://github.com/anburocky3/iragugal-web)

**Comment by anburocky3** [comment]
> ```diff
> plugins: ['@/plugins/persistedstate.universal.ts'],
> ```

Even if i add it to `nuxt.config.ts`  still i see this error?

![image](https://user-images.githubusercontent.com/15264938/163978213-dee616d9-3c3e-4eed-8c86-8e9109799e57.png)

**Comment by iendeavor** [comment]
Try moving `const xxxStore = useXXXStore();` into the function `defineXXXMiddleware` in `./middleware/guest` and `./middleware/auth`.

https://github.com/anburocky3/iragugal-web/blob/main/middleware/auth.ts#L3

**Comment by anburocky3** [comment]
Thanks, that fixes it. Thank you.

Will close this for now, will reopen if i have any similar error in the future.
