### ISSUE TITLE
`assertStorage` should be `async`

### ISSUE THREAD

**Issue by Tanimodori** [iendeavor/pinia-plugin-persistedstate-2#218]
**Is your feature request related to a problem? Please describe.**

`assertStorage` should be `async` to ensure external data source is available before any r/w can be done.

**Describe the solution you'd like**

`assertStorage` should be `async`

**Describe alternatives you've considered**

...or you'll need to call it every time before each r/w ops.

**Additional context**

I use a json file as storage which need to be created in async. Yeah you can create in sync mode but the whole library is for those who need async ops.

**Comment by iendeavor** [comment]
Thanks you for your feedback ❤️ .

This issue is fixed, and will be released in next patch version.
