### ISSUE TITLE
It can only be used in the vue file, not in the ts file, and there is no way to persist it in the ts file

### ISSUE THREAD

**Issue by 17607106326** [iendeavor/pinia-plugin-persistedstate-2#24]
It can only be used in the vue file, not in the ts file, and there is no way to persist it in the ts file
![2022618121822](https://user-images.githubusercontent.com/50573299/174422628-2c69bc90-105f-4bcf-ab4c-94bd8c91c0b0.jpg)
This can be written to be persistent。
![2022618122048](https://user-images.githubusercontent.com/50573299/174422633-5b5248ce-c457-44cc-b43b-95a1594fc700.jpg)
This write cannot be persisted。

**Comment by 17607106326** [comment]
This can be written to be persistent。
![2022618121822](https://user-images.githubusercontent.com/50573299/174422698-9e742651-ebf6-4980-9277-6f2e93ed26c5.jpg)

**Comment by 17607106326** [comment]
This write cannot be persisted。
![Uploading 2022618122048.jpg…]()

**Comment by iendeavor** [comment]
It's not a bug, the way you're using it in the first image works because it's in the `setup` context (`<script setup>`) , but the second image isn't.

Please check this: https://pinia.vuejs.org/core-concepts/outside-component-usage.html .

**Comment by 17607106326** [comment]
thank you so much
