### ISSUE TITLE
help zod validation before 

### ISSUE THREAD

**Issue by reslear** [iendeavor/pinia-plugin-persistedstate-2#266]
hi @iendeavor what is the best way to check the data with zod parse before persist?

**Comment by iendeavor** [comment]
IMO, the states itself should be valid during entire application lifecycle, hence we should validate _new_ states before (i.e., initialization, in actions, during hydration) assign it to store.

So we don't need to validate it during persistent.

**Comment by reslear** [comment]
For example, LocalStorage changed by user manually String, and we set String, but expect Number. for this better use `merge` method?

**Comment by iendeavor** [comment]
What kind of your app is? Why users would manually change LocalStorage?

**Comment by reslear** [comment]
two apps on one page with the same local storage, and the user change state from another app
