### ISSUE TITLE
use this repo for vite-plugin-ssr plugin

### ISSUE THREAD

**Issue by hamedg68** [iendeavor/pinia-plugin-persistedstate-2#32]
how can I add this plugin to vite-plugin-ssr plugin (https://github.com/brillout/vite-plugin-ssr)?, I got error.

**Comment by hamedg68** [comment]
it works for client routing but after hydration does not work

**Comment by hamedg68** [comment]
here is a reproduction showing the problem 
https://stackblitz.com/github/hamedg68/vps-pinia-persist
if open link (http://localhost:3000/star-wars) directly movies list dont not store in local storage

**Comment by iendeavor** [comment]
Because the [Counter component](https://github.com/hamedg68/vps-pinia-persist/blob/c08e66cd81236a16fe534d9a33a3ad840f23b7ec/components/Counter.vue) doesn't use pinia store.
