### ISSUE TITLE
Cant persist on nuxt 3 rc 9

### ISSUE THREAD

**Issue by capoia** [iendeavor/pinia-plugin-persistedstate-2#33]
Hi, first I wanted to thank you for the library.
And I also wanted to inform you that the example using nuxt3 does not work, not even in codesandbox.

I tried to follow the examples, but no cookie was created, I put a console.log in the get and set functions, to see what was going on and it returns the key '@@' and the value '1'.

Plugin: 
![image](https://user-images.githubusercontent.com/21159928/188503525-1951e37f-57d2-4bc2-9216-0506d36160be.png)

Store:
![image](https://user-images.githubusercontent.com/21159928/188503468-2b845174-776e-48f5-b86d-664c193fb462.png)

Console.log

![image](https://user-images.githubusercontent.com/21159928/188503551-15d6c839-0224-4100-89bb-1a5c0101a4f7.png)

**Comment by iendeavor** [comment]
Thank you for your bug report!
Much appreciate! 🙏

This should be fixed by https://github.com/iendeavor/pinia-plugin-persistedstate-2/commit/7f62ac938bbb83f142f361620b9297be9e7feae0 .
