### ISSUE TITLE
implement global key prefix 

### ISSUE THREAD

**Issue by reslear** [iendeavor/pinia-plugin-persistedstate-2#4]
add option, to add and strip prefix for localstorage

```
createPersistedStatePlugin({
  prefix: '_p_'
})
```

like have store with name `account` in localstorage key - `_p_account`

**Comment by iendeavor** [comment]
It is more flexible to provide a `function` plugin option:

```ts
const identity = _ => _

createPersistedStatePlugin({
  alterKey: (storeKey: string) => string = identity
})
```

Feel free to pull request 😄 .

**Comment by reslear** [comment]
Yes, it will be relevant only for localstorage, like sugar for no copy-past setItem,getItem )
