### ISSUE TITLE
Can not work on object type

### ISSUE THREAD

**Issue by pipinet** [iendeavor/pinia-plugin-persistedstate-2#5]

**Comment by iendeavor** [comment]
Thanks for your feedback, but what do you mean by "object type"?

**Comment by iendeavor** [comment]
Thanks for your feedback, but what does "object type" stand for?

**Comment by pipinet** [comment]
@iendeavor  state some field is an object

**Comment by iendeavor** [comment]
Could you provide a codesandbox or reproduce steps?

I created an example for the object state and it seems to work well:

https://codesandbox.io/s/pinia-plugin-persistedstate-2-issues-5-y3dmb

`src/stores/counter.ts`:
```ts
import { defineStore } from 'pinia'

export const useCounterStore = defineStore('counter-store', {
  state: () => {
    return {
      path: {
        to: {
          count: 0,
        },
      },
    }
  },
})
```

`src/app.vue`:

```vue
<script setup lang="ts">
import { useCounterStore } from './stores/counter'

const counterStore = useCounterStore()
</script>

<template>
  <button type="button" @click="counterStore.path.to.count++">
    count is: {{ counterStore.path.to.count }}
  </button>
</template>
```

**Comment by plainlystated** [comment]
I found this issue when I was dealing with a similar-sounding problem.  Not sure if it is what the original poster meant or not, but this plugin doesn't support instantiated ES6 classes in the store.  They lose the class during serialization.

If the serializer for this plugin could be specified per-store, then it would be easy to build the objects based on known classes for the known data structure.

For me, I worked around it another way, but wanted to drop this comment in case anyone else came here with this problem.

**Comment by iendeavor** [comment]
@plainlystated  The per-store serializer option is defined in common options 😅:

https://github.com/iendeavor/pinia-plugin-persistedstate-2#common-options

**Comment by plainlystated** [comment]
@iendeavor Oh, nice!  I didn't realize you could use those common options on the stores.  Thanks for letting me know!

**Comment by plainlystated** [comment]
I refactored my code and got it working.  I like the approach.  Putting it below in case it's helpful to anyone that comes across this in the future.  (My JS/typescript is pretty rough but it works.)

```
  persistedState: {
    serialize(state: any): string {
      const simpleState: {items: CartItemParams[]} = {
        items: state.items.map((item: CartItem) => ({slug: item.product.slug, quantity: item.quantity}))
      }
      console.log('serializing', simpleState)
      return JSON.stringify(simpleState)
    },
    deserialize(value: string): {items: CartItem[]} {
      const ret = JSON.parse(value)
      ret.items =  ret.items.map((params: CartItemParams): CartItem => new CartItem(params))
      console.log('loading', ret)
      return ret
    }
  },
```

@iendeavor  Thanks for the help (and the project itself)!
