### ISSUE TITLE
(Wish) Persist plugin works for each module.

### ISSUE THREAD

**Issue by initred** [iendeavor/pinia-plugin-persistedstate-2#6]
**Is your feature request related to a problem? Please describe.**

I wish I could give you an option so that the persist plugin can work for each module.

**Describe the solution you'd like**

ex) Currently, this plug-in works for all modules in Pinia.
What I'm trying to do is make it work only on the auto module, but it all works regardless.

**Describe alternatives you've considered**

Can't the module solve it in the form of an option boolean?

```
createPersistedStatePlugin({
//storeId in array
  active: ['auth'] 
})
```
or 

```
// ...
const store = defineStore(
  'store',
  () => {
    return {
      // oldKey: ref(0),
      newKey: ref(0),
    }
  },
  {
    persistedState: {
      active: false
  },
)()
```

**Additional context**

Thank you for your hard work and leave an issue in the hope of adding these functions.

**Comment by iendeavor** [comment]
@initred 

You could use [`persist` option](https://github.com/iendeavor/pinia-plugin-persistedstate-2#common-options):

```ts
createPersistedStatePlugin({
  persist: true // persist by default
})
```

```ts
const useStore = defineStore(
  'store',
  () => {
    return { /* ... */ }
  },
  {
    persistedState: {
      persist: false // disable it
  },
)
```

Maybe we should use another *name*? e.g., `active`, or `enabled`.

Thanks you for your feedback 😄 .

**Comment by initred** [comment]
I must have misinterpreted English a little. 

As you answered, you are good at functioning. 

It's been confirmed that it's. Thank you. 😄

I don't think I need to change the name. It's such a good plug-in. Thank you.

Thank you for your effort.

This issue is my mistake, so I'll close it.
