### ISSUE TITLE
Need .cjs extensions instead of .js

### ISSUE THREAD

**Issue by L422Y** [iendeavor/pinia-plugin-persistedstate-2#72]
This file is being treated as an ES module because it has a '.js' file extension and '.../node_modules/pinia-plugin-persistedstate-2/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

**Comment by plainlystated** [comment]
Hitting this as well.  Any way to work-around this in the meantime?

**Comment by L422Y** [comment]
> Hitting this as well. Any way to work-around this in the meantime?

I just went in and renamed things myself in the interim

**Comment by mbadr2200** [comment]
same issue but with the build not working 

> > Hitting this as well. Any way to work-around this in the meantime?
> 
> I just went in and renamed things myself in the interim

**Comment by iendeavor** [comment]
Thanks for your feedback, this fix has been released in v2.0.3.
