### ISSUE TITLE
Cannot add to localStorage in composable / module

### ISSUE THREAD

**Issue by michelwaechterimflow** [iendeavor/pinia-plugin-persistedstate-2#8]
**Describe the bug**
It added two stores (createCities and user). the createCities store i $patch in an component and it works really fine. I can see the store-data in my local storage. The city data I $patch in an module (./src/composables/strapi/auth) and the userData never enters the localStorage.. the code in store definition is truely the same.. pinia devtolls tell me, that user store is initialised.. what can i do?

user.js

`import {
      defineStore
} from 'pinia'

export const useUserStore = defineStore({
      id: 'user',
      state: () => {
            return {
                  user: {},
                  token: '',
            }
      },
      persist: {
            enabled: true,
            key: 'user',
      },

})`

createCity.js

`import {
    defineStore
} from 'pinia';

export const useCreateCityStore = defineStore({
    id: 'createCity',
    state: () => {
          return {
                newCity: {},
                step: 1,
          }
    },
    persist:
    {
        enabled: true,
        key: 'createCity',
    },

})`

auth.js

`await axios.post(`${API_URL}/auth/local`, {
            identifier: identifier.value,
            password: password.value
        })
        .then(response => {
            const tempUser = response.data.user;
            if (tempUser.confirmed && !tempUser.blocked) {
                await store.$subscribe({
                    user: response.data.user,
                    token: response.data.jwt
                });
                console.log(`user: ${JSON.stringify(store.user)}`);
                console.log(`token: ${JSON.stringify(store.token)}`);
                result = {
                    error: false,
                    message: 'Login successful',
                };
            } else {
                result = {
                    error: true,
                    message: 'Please confirm your email',
                };
            }
        })`

(it is also added to store.. but lost after redirect or anything.. you know)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS M1
- Browser [e.g. chrome, safari] Chorme

**Additional context**
Can you give me any help to solve this..?

**Comment by iendeavor** [comment]
@michelwaechterimflow Hi, I think you may have another plugin installed, you can see in `package.json` which package you have installed and then report the issue to that package.

If you want to use this package, you can follow the instructions [here](https://github.com/iendeavor/pinia-plugin-persistedstate-2#installation) and [there](https://github.com/iendeavor/pinia-plugin-persistedstate-2/tree/main/examples/vue3-example) is a real example.

Hope this helps you :smile:.
